general_cfg:
  algo_name: PPO-KL
  device: cpu
  env_name: CartPole-v1
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: false
  load_path: Train_CartPole-v1_PPO-KL_20221206-054757
  max_steps: 200
  mode: train
  new_step_api: true
  render: false
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 200
  wrapper: null
algo_cfg:
  KL_alpha: 2
  KL_beta_high: 1.5
  KL_beta_low: 0.6666666666666666
  KL_lambda: 0.5
  KL_target: 0.01
  actor_hidden_dim: 256
  actor_lr: 0.0003
  critic_hidden_dim: 256
  critic_lr: 0.0003
  entropy_coef: 0.01
  gamma: 0.99
  k_epochs: 4
  update_freq: 100
